# Generated by Django 2.1.7 on 2019-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('otype', models.IntegerField(choices=[(0, 'BID'), (1, 'ASK')])),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
